// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/fiqriardiansyah/user-shopping-api-golang/internal/helper"
	"github.com/fiqriardiansyah/user-shopping-api-golang/internal/module/auth/repository"
	"github.com/fiqriardiansyah/user-shopping-api-golang/internal/module/auth/usecase"
	"github.com/go-playground/validator/v10"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAuthHandler(db *gorm.DB, validator2 *validator.Validate, config *helper.Config) *AuthController {
	authRepository := repository.NewAuthRepository()
	authUseCase := usecase.NewAuthUseCase(authRepository, db, config)
	authController := NewAuthController(authUseCase, validator2, config)
	return authController
}
