// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/fiqriardiansyah/user-shopping-api-golang/internal/helper"
	"github.com/fiqriardiansyah/user-shopping-api-golang/internal/module/user/repository"
	"github.com/fiqriardiansyah/user-shopping-api-golang/internal/module/user/usecase"
	"github.com/go-playground/validator/v10"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeUserHandler(db *gorm.DB, validate *validator.Validate, config *helper.Config) *UserHandlerSet {
	userRepository := repository.NewUserRepository()
	userUseCase := usecase.NewUserUseCase(userRepository, db)
	userController := NewUserController(userUseCase, validate, config)
	userHandlerSet := &UserHandlerSet{
		Controller: userController,
		UseCase:    userUseCase,
	}
	return userHandlerSet
}

// wire.go:

type UserHandlerSet struct {
	Controller *UserController
	UseCase    *usecase.UserUseCase
}
